language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "cookie-exchange:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: zNGOtj/58j//vYZZPLArWaX9DkSEE1y2du3BoSyfP7Rd1XFdJGK+KwPTSOge+EF960skeii3dAtMdlz0sIpx//MZhqaBI9KAw03ec/dnsEdwQTg0Y66oAPxfdkIy5Ea9Ligh6BYbpyw/OZCDjlwze0vyLSa9zjITN4pC/QzGbtgfGaH1BX0qYFHSyPSv9XkMt3VxBOeMLq4CFMRNFBUyDgEdteXfSZgeOcgMkCn7qqv/MLTUc+rAEeaKVssLkGTRoACFS70lwGPKV3ENVOwfOULRm0lR32grzn3IZxdnTnLHp/wUfV7U0zCES91qcDfUp8tKPA8X5SyT/UTgaBfCqBMmpYzMfM5N7tQ+wVq8yEcqVtoOmDMxXB5JDeWqzeTjkpNpw6Y332Mvx8wQBHiGMn8R+k30OZbtfjvRqhc9lyZcGgulB8xypZz62vtZM+NG6Q7UuRNCIIuFfkJZ9/iZDZAPAwjWYJdnM979Dp7nNs0UEIimp3e5umZlVNNJddz4iWlV/6VFADdaJXcDneSReuWT6GTPrV7xqMRibDcVfLL8uNjQZtrhDMNeS0ookdi2tNlXPV7JY/pxouPDfa875fFrhf/fTXVBmhXz4S/2AoH/dgvGs1xP0DBrfoBqPMQkE1jrlANlYmBnkZyO4jiVDbAjJsMqbRP+w/GTKmgo/Ds=
  - secure: FCK1/KXQqj6E31evVWil963xaKSB3w99/0niNH7IMxPhKjtuGwjJAfu7UNOoP2lqKs/m7EeyEeW7nZaVJuPvHPNfMYjFuBGdsffIoI27VyNWzcwijg7lDQ6mIN7pY8yPFEjKwgtDeJcIKlk5LZOdhFf0tqh7wInAQavwSd5HpGq6gDRIx5eynUDL7qcD0CxVw10hUMj/UZZMtJRMcCtFgn3as3H3zJr+Qe3LmH/4nG7l4x4xxWrFafqzdWONev7CMYMWmNCY5ca1ypMF9CG9j/rJULkOjyIrWJT9Lo7E2KHJ8R4fyyps8DvUVOlHR2Iu7YXV3Vd1fhx+o2wWm1KcEa8gE1Qqh/LLVdf4FIyNrWL6ZqvbJTbpNtOHXnvFJ1+ItEJjWr9ossZNwjsfJrhEpEd9lFViZ8d9C+JBOjFRslyxmXozGKjcV0z+U/k4q0XeDbBLI++vFsbYMwEOke3NQUc7pChHpRdk+Ji2qpXMcDaHUjbCMoTpZXq51cqdWUP1VDnnS82haYBOdGQGJJumvtfDfSMG0az9p6zpjCo5/7T2jS+LPqzU7QattgThXac2iOR0iuqqgt3GxamUDKkrVetlCSr4fZc0+rO+hoVDh+IVkWUIMsixiAASTqVGJ8+zhQrMTDKO+TWd5MUg91G2IA7O0cpkCLuV3bEyoOd4kHE=
